# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aee7d25b48f2dd121ce3d12f54182af80961c7fe0b125058806967cfb077232ef15668b233711e85ad9b7e40ee562f5a29980ce158414fc5bd26a00edd804e5c

test:
  secret_key_base: 0971ead8bc627c6c0c768350eba64c0f06044c04f8d2d5b959dbd8748a8066f4da5e5581d07e8c4b36f4be1441061e2bccdaf9117562d3ab6510e2209fc16041

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
